version: '3.1'
services:
  minio:
    image: quay.io/minio/minio
    networks:
      - airflow
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
       - ${PWD}/include/minio:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    restart: always
    env_file: .env

  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8501:8501
      - 8502:8502
    networks:
      - airflow

  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow

  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow

  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow

  user-postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "25432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "15051:80"
    depends_on:
      - user-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    networks:
      - airflow


  mlflow:
    image: ghcr.io/mlflow/mlflow
    networks:
      - airflow
    command: bash -c '(pip install -q boto3) && (mlflow server --host 0.0.0.0 --backend-store-uri sqlite:////data/mlflow_backend.db --default-artifact-root s3://mlflowdata)'
    volumes:
      - ${PWD}/include/mlflow:/data
    ports:
      - 5005:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file: .env

volumes:
  user_postgres_data:

networks:
  airflow:
    driver: bridge